services:
  - type: web
    name: cricshot
    env: python
    region: singapore
    plan: free
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --preload"
    envVars:
      - key: MAIL_SERVER
        value: mail.smtp2go.com
      - key: MAIL_PORT
        value: "2525"
      - key: MAIL_USE_TLS
        value: "True"
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: SECRET_KEY
        generateValue: true
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        sync: false
      - key: TWI_ACCOUNT_SID
        sync: false
      - key: TWI_AUTH_TOKEN
        sync: false
      - key: TWI_PHONE_NUMBER
        sync: false
      - key: TURSO_DATABASE_URL
        value: libsql://cricshotdb-revanth14.aws-ap-south-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false
